name: Build
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
    steps:
      - uses: actions/checkout@v5
        with:
          repository: neveler/HMCL-docs
          ref: dev-i18n-data
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: build
        run: |
          echo "url: https://hmcl-docs.github.io" > build/action.yml
          echo "footer:" >> build/action.yml
          echo "  links:" >> build/action.yml
          echo "    - label: Github" >> build/action.yml
          echo "      icon: fab fa-fw fa-github" >> build/action.yml
          echo "      url: https://github.com/HMCL-dev/HMCL" >> build/action.yml
          bash build/setup.sh build/action.yml
          cd _site
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git init && git add .
          git commit -m "Deploy [skip ci]" || echo "No changes to commit"
          git checkout -b site
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin site -f
